### ISSUE TITLE
[exerciceset] Demande de route ou modification du post/put

### ISSUE THREAD

**Issue by loverg-c** [xAt0mZ/EIP_server#1]
Pour l'instant impossible de creer un exerciceset et de le lier à un utilisateur/module, si ya moyen de linker ça pendant le post/put ou de creer une route exprès :)

**Comment by xAt0mZ** [comment]
/exercicesets/templates/{id}/register

La route crée un exerciceset pour le module.
Il faut être register au module pour pouvoir effectuer le register sur le moduletemplate


En gros, normalement, on ne POST ni PUT directement un Module / ExerciceSet

Il faut utiliser les /{id}/register sur les Templates respectifs pour s'inscrire (et /{id}/unregister pour se désinscrire) et créer les Module et ExerciceSet
