### ISSUE TITLE
DELETE ??

### ISSUE THREAD

**Issue by martres** [xAt0mZ/EIP_server#16]
Hello pour faire un delete d'un cours c'est bien comme ça ? 

http://51.254.99.218:8080/server/api/courses

{
"id" : "577ef2cf77490b0001737655"
}

Il faut autre chose ?

**Comment by xAt0mZ** [comment]
Nop c'est tout bon.

**Comment by martres** [comment]
J'ai un 403 quand je fais ça avec Postman

**Comment by xAt0mZ** [comment]
Je viens de le faire, ça fonctionne.
![2016-08-30-122023_1920x1080_scrot](https://cloud.githubusercontent.com/assets/7642331/18081649/859d8286-6e9b-11e6-8455-a7f530b41ef4.png)
