### ISSUE TITLE
[absence][bug] Get & get /id

### ISSUE THREAD

**Issue by loverg-c** [xAt0mZ/EIP_server#3]
Get sur /absences me renvoit
org.mongodb.morphia.mapping.MappingException: Could not map com.esb.server.entities.management.Absence with ID: 57bef8c646e0fb0001768486 in database 'eschoolbag'

et get sur /absences/57bb1889c9e77c0001180e3a me renvoit
57bb1889c9e77c0001180e3a (ou no response from server par swagger)

**Comment by xAt0mZ** [comment]
Les users mis dans les absences sont invalides (inexistants).
J'ai delete toutes les entrées de la base qui étaient buggéed
