### ISSUE TITLE
[absence][delays][bug] get absences/{id} delays/{id} modules/{id}

### ISSUE THREAD

**Issue by loverg-c** [xAt0mZ/EIP_server#5]
No content avec http://51.254.99.218:8080/server/api/absences/57bb1889c9e77c0001180e3a (id pourtant existant)

No content avec http://51.254.99.218:8080/server/api/delays/573bf796dc0e8200015c77ad (id pourtant existant)

No content avec http://51.254.99.218:8080/server/api/modules/templates/73bf796dc0e8200015c77be (id pourtant existant)

**Comment by xAt0mZ** [comment]
1. Fixed by pull request #7 
2. C'est l'id d'un user dans l'url.
3. Il manque 1 caractère dans l'id.

**Comment by loverg-c** [comment]
my bad pour les deux autres, absences toujours pas :/

**Comment by xAt0mZ** [comment]
C'est corrigé.
